### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by cvionis** [cvionis/network-keys#1]
- [x] Clear terminal when program is run
- [x] Make it more clear what the user inputted in the terminal
- [x] Hide debugging info printed when export command is used
- [x] Create a shell script to delete profile info files after script stops running 
- [ ] Implement error handling (specifically to ensure deletion of profile info files if an error is encountered when script is run)
- [x] Add documentation to code to improve readability
